name: gophermart
services:

  pgsql:
    env_file:
      - .env
    image: 'postgres:14'
    container_name: gophermart_pgsql
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE:-gophermart}'
      POSTGRES_USER: '${DB_USERNAME:-gophermart}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pgsql_data:/var/lib/postgresql/data'
    networks:
      - gophermart_network
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s

  accrual:
    container_name: gophermart_accrual
    build:
      context: .
      dockerfile: docker/accrual/Dockerfile
    ports:
      - '${ACCRUAL_PORT:-8081}:8081'
    networks:
      - gophermart_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/orders/12345678903"]
      interval: 5s
      timeout: 3s
      retries: 3

volumes:
  pgsql_data:
    name: gophermart_pgsql_data
    driver: local

networks:
  gophermart_network:
    name: gophermart_network
    driver: bridge
    external: false
